### ISSUE TITLE
How to make a test between rooms

### ISSUE THREAD

**Issue by Totobal5** [YoYoGames/GM-TestFramework#47]
I am making a test for my games to see if a object is persistent between rooms, i am trying to see examples in the project but it appear that there is no way to test between rooms.

**Comment by DiasFranciscoA** [comment]
It is completly possible to test accross just I just added a sample for you to follow just sync to the develop branch and look into the `BasicRoomTestSuite` you will need to use asynchronous tests.

**Comment by Totobal5** [comment]
Using the new version throw this error when runing the test

```
ERROR!!! :: ############################################################################################
ERROR in
action number 1
of Other Event: Room End
for object oEvents:


Variable <unknown_object>.performEventTest(101466, -2147483648) not set before reading it.
 at gml_Object_oEvents_Other_5 (line 2) - performEventTest(object_index, event_type, event_number);
############################################################################################
gml_Object_oEvents_Other_5 (line 2)

```

Some clue why ?

edit:

you just need to remove the `room_change` in the [objTest](https://github.com/YoYoGames/GM-TestFramework/blob/680631d2398fe586adc616b75d820172ac2bca9f/projects/xUnit/objects/objTest/Create_0.gml)
