### ISSUE TITLE
Extend string_concat() and string_join() to test combinations of strings with variables

### ISSUE THREAD

**Issue by gnysek** [YoYoGames/GM-TestFramework#78]
### Description

There was recently an issue, in which `string_concat`, and `string_join`, were failing under very specific condition - if penultimate argument was a variable name, and last argument was a literal string - https://github.com/YoYoGames/GameMaker-Bugs/issues/6480 .

Basic idea is to extend `BasicStringTestSuite` for those functions (and their `_ext versions`, to include such specific cases too.

### Steps To The Task

- [x] `string_concat`, `string_concat_ext` - 1st arg is variable, 2nd arg is string
- [x] `string_concat`, `string_concat_ext` - 1st arg is string, 2nd arg is variable
- [x] `string_join`, `string_join_ext` - 2nd arg is variable, 3rd arg is string
- [x] `string_join`, `string_join_ext` - 2nd arg is string, 3rd arg is variable

**Comment by gnysek** [comment]
@YYDan there's issue with contributing:
> 3. Back on your issue in our repository, set the branch in the right-hand side to be a new branch back on your own fork

Nothing is clickable for users outside of YYG in right side panel, that's how it looks on my side:

![obraz](https://github.com/YoYoGames/GM-TestFramework/assets/524094/780e0a43-eba8-4ae8-944a-38db00e87c36)

**Comment by YYDan** [comment]
Yeah, I am looking into a few issues for external contributors at the moment, but thanks for letting me know.
